### ISSUE TITLE
immagini non mostrate, credo per via del link errato

### ISSUE THREAD

**Issue by erinrrr** [sapienzastudentsnetwork/sapienzastudentsnetwork.github.io#48]
riga 32 e ria 43 in biblioteche.md:
![ciao](link che non porta a niente)

non so se errore nel link ma non funziona

**Comment by ElBi21** [comment]
Ciao, sì, dobbiamo ancora finire di portare le immagini da un vecchio prototipo, lo faremo penso nei prossimi giorni!

**Comment by Lorenzoantonelli** [comment]
Fixato con il commit: [4c219132fc40e80425a0be27000531e8088949dc](https://github.com/sapienzastudentsnetwork/sapienzastudentsnetwork.github.io/commit/4c219132fc40e80425a0be27000531e8088949dc)

**Comment by matypist** [comment]
Risolto, @erinrrr , grazie per la segnalazione :smiley:
