### ISSUE TITLE
Aggiunta relazione di tirocinio

### ISSUE THREAD

**Issue by LucianCrainic** [sapienzastudentsnetwork/sapienzastudentsnetwork.github.io#51]
> [!IMPORTANT]
> Allega a questa issue il link o il file della relazione di tirocinio. Per caricare la relazione è necessario selezionare tutte e tre le tre caselle qui sotto, aggiungendo una `x` su ognuna.

[full-version.pdf](https://github.com/user-attachments/files/17007434/full-version.pdf)
Thesis in English but done for the BSc in Computer Science. Title: Machine Learning for Human Movement Classification Based on Kinect Skeleton Data.

Happy to contribute to such a great resource that will help many students to come :) .

Aggiungendo questa relazione di tirocinio alla pagina dichiaro che:
- [x] sono l'autore della relazione di tirocinio o ho ricevuto l'autorizzazione per condividerla dall'autore
- [x] desidero condividere la relazione di tirocinio con gli studenti sulla pagina https://sapienzastudents.net/it/info/terzo-anno/tirocinio/
- [x] posso richiedere la rimozione della relazione di tirocinio in qualsiasi momento aprendo una nuova issue su GitHub

**Comment by LucianCrainic** [comment]
@Lorenzoantonelli it's a bit hard to find the uploaded thesis in the website, since they offer a lot of value to students it shall be more easy to get to the list. I would put the drop down menu or a direct link to it at the top of the "Tirocino" page like you did with the Telegram group link. Both are important resources.

Cheers.

**Comment by Lorenzoantonelli** [comment]
Thank you @LucianCrainic for your valuable contribution and for the useful tip!❤️ We have added your thesis and a tip next to the one related to groups at the top of the page.
